version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key
    command: python app.py
    restart: unless-stopped 