version: '3.8'

services:
  web:
    build: .
    ports:
      - "5500:8000"
    volumes:
      - .:/app
      - ./static:/app/static:rw
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key
    restart: unless-stopped 
